### PR TITLE
Workflow streamlined with respect to authenticating and cache updating

### LINKED ISSUE #1: Only pulls the first 30 repos
It appears as if this script only pulls the first 30 repos for each user/organization. I'm going to look into making a pull request to patch this, just a heads up! I love how quick and responsive this is, but the 20 repo limitation is a killer for me.

It's probably because of this limitation, which we could just boost to an enormous number to solve the problem: https://developer.github.com/v3/#pagination

### PR DESCRIPTION
**Pull request by mklement0**
- If a search finds no result, you're now given the option to update the cache right there, and to repeat the search after.
- If no token has ever been set or it is invalid, you can switch over to gh-auth simply by actioning the error message.
- gh-auth without an argument now opens https://github.com/settings/tokens/new to facilitate creating a token.

README.md has been updated accordingly, and some copyediting was performed.

- Bugfix (fixes #1): the number of repos retrieved is no longer limited to 30.

### CODE REVIEW

**Comment by jfairley** [comment]
:+1: Would love to see this (or something akin) merged in. I belong to an organization with over 100 repositories (not to mention all of my forks).

Thanks to @mklement0 and @jenius for their contributions!

**Comment by jfairley** [comment]
Although considering the lack of activity here, I'll be using this as an alternative...
https://github.com/gharlan/alfred-github-workflow

**Comment by michaeltarleton** [comment]
While this PR fixed my issue... it doesn't look like it will be merged let alone maintained in the future so for now https://github.com/gharlan/alfred-github-workflow does indeed resolve my current need.

Thanks @jfairley for the recommendation.
Thanks @mklement0 and @jenius for your contribs.

**Comment by mklement0** [comment]
Thanks, @jfairley  and @michaeltarleton. Bummer that this was abandoned, but I'm glad you found an alternative; I'll take a look myself.

**Comment by michaeltarleton** [comment]
@mklement0 if someone were to fork this and everyone could send their PRs to that fork, I'd still use this one. To me it's fast and does exactly what I need.

**Comment by mklement0** [comment]
@michaeltarleton I'll consider it. Is speed the only issue you have with the alternative?

**Comment by michaeltarleton** [comment]
@mklement0 Well now that I checked again, it does seem to be caching it's very quick now. So I guess the new plugin is prly what I'll stick with. Also, It does seem to be much more active than this one.

**Pull request merged**
